fix undefined processExists error (#87)
* fix error
daemon/daemon.go:90:5: undefined: processExists
just a copy of daemon_darwin

* remove openbsd and rename daemon_unix
also update the build contraints

* update the build contraints

* this got added by vscode

* added the rest of the systems that should work with this
file without a problem

* Exclude linux & windows instead
now we support more platforms out of the box